In [ ]:
## Using Pandas functions

In [2]:
## Load muckrackers

import pandas as pd
import numpy as np

In [3]:
## Putting the state data in a dictionary
state_data =  {'State':['Alabama','Alaska','Arizona','Arkansas'],'PostCode':['AL','AK','AZ','AR'],'Area':['52,423','656,424','*','53,182'],'Pop':['4,040,587','550,043','3,665,228','2,350,750']}
state_data

{'State': ['Alabama', 'Alaska', 'Arizona', 'Arkansas'],
 'PostCode': ['AL', 'AK', 'AZ', 'AR'],
 'Area': ['52,423', '656,424', '*', '53,182'],
 'Pop': ['4,040,587', '550,043', '3,665,228', '2,350,750']}

In [6]:
## Loading the dictionary data into a df with the specified columns. 

my_df = pd.DataFrame(state_data,columns=['State','PostCode','Area','Pop'])

In [7]:
## Checking if I screwed up
my_df

      State PostCode     Area        Pop
0   Alabama       AL   52,423  4,040,587
1    Alaska       AK  656,424    550,043
2   Arizona       AZ        *  3,665,228
3  Arkansas       AR   53,182  2,350,750

In [8]:
## Indexing my df by the state name
my_df = my_df.set_index('State')

In [9]:
## Did it work?
my_df

         PostCode     Area        Pop
State
Alabama        AL   52,423  4,040,587
Alaska         AK  656,424    550,043
Arizona        AZ        *  3,665,228
Arkansas       AR   53,182  2,350,750

In [12]:
## Create function that replaces all * with 0 values.
def star_replace(i):
    return i.replace('*','0')
## For my df column 'Area' replace with a copy that's had the star_replace function run on it. 
my_df['Area'] =my_df['Area'].map(star_replace)

In [13]:
my_df

         PostCode     Area        Pop
State
Alabama        AL   52,423  4,040,587
Alaska         AK  656,424    550,043
Arizona        AZ        0  3,665,228
Arkansas       AR   53,182  2,350,750

In [14]:
# Create a function that takes an object as input, and runs the replace function over it,
## replacing all commas with blanks. 

def comma_replace(i):
    return i.replace(',','')

## Run that function across the Area and Pop fields

my_df['Area'] = my_df['Area'].map(comma_replace)
my_df['Pop'] = my_df['Pop'].map(comma_replace)
my_df

         PostCode    Area      Pop
State
Alabama        AL   52423  4040587
Alaska         AK  656424   550043
Arizona        AZ       0  3665228
Arkansas       AR   53182  2350750