In [11]:
## Load muckrakers
import pandas as pd

In [12]:
## Load information into a usable  df

persondict = {'person':['Bob','Alice','Steve'],'age':[32,24,64],'weight':[128,86,95]}
my_df=pd.DataFrame(persondict, columns=['person','age','weight'])
my_df

  person  age  weight
0    Bob   32     128
1  Alice   24      86
2  Steve   64      95

In [13]:
## Reset the index to be the person column 
my_df = my_df.set_index('person')
my_df

        age  weight
person
Bob      32     128
Alice    24      86
Steve    64      95

In [14]:
## Stack the df
result = my_df.stack()
result

person
Bob     age        32
        weight    128
Alice   age        24
        weight     86
Steve   age        64
        weight     95
dtype: int64

In [15]:
## Reset the index
tall_df = result.reset_index()
tall_df

  person level_1    0
0    Bob     age   32
1    Bob  weight  128
2  Alice     age   24
3  Alice  weight   86
4  Steve     age   64
5  Steve  weight   95

In [16]:
## Rename the columns

tall_df.columns=['person','attribute','value']
tall_df

  person attribute  value
0    Bob       age     32
1    Bob    weight    128
2  Alice       age     24
3  Alice    weight     86
4  Steve       age     64
5  Steve    weight     95

In [17]:
## Convert back to the original shape
result.unstack()

        age  weight
person
Bob      32     128
Alice    24      86
Steve    64      95

In [18]:
# There was an issue with this... You seem to have to specify the argument name. 
tall_df.pivot(index ='person',columns='attribute',values='value')

attribute  age  weight
person
Alice       24      86
Bob         32     128
Steve       64      95